### ISSUE TITLE
"Cannot find module './ko.yml" error

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/engine#29]
![image](https://user-images.githubusercontent.com/6451384/101278190-2875e280-37fd-11eb-9490-69c59f24cb99.png)

Hello, Ilya and the Team!

I've got the report from the Korean users that there is problem on the Tasks section

You could refer the image on the top.

Let me know what I can do or let me know if the issue can be resolved.

Thanks as always!

**Comment by Violet-Bora-Lee** [comment]
https://github.com/javascript-tutorial/engine/pull/30

I've made new PR to resolve the issue

Could you check and merge?

**Comment by Violet-Bora-Lee** [comment]
@iliakan

**Comment by iliakan** [comment]
Thanks for mentioning me, @Violet-Bora-Lee ! Please don't hesitate to do so.
PR merged.

**Comment by Violet-Bora-Lee** [comment]
Thanks, @iliakan 
However, the same issue is reproduced. 😭 😭

**Comment by iliakan** [comment]
The PR didn’t help? Did you git pull?

**Comment by Violet-Bora-Lee** [comment]
You could check that the issue hasn't resolved on the ko.javascript.info 😥

**Comment by iliakan** [comment]
@Violet-Bora-Lee I made a few changes, please pull the server. What's wrong with ko.javascript.info? Give me a screenshot of the error?

**Comment by Violet-Bora-Lee** [comment]
Every code box dosen't working well. You can reproduce the issue very easily.

**Comment by iliakan** [comment]
Thanks, fixed!

**Comment by Violet-Bora-Lee** [comment]
Got it! 👍

**Comment by iliakan** [comment]
I'm thinking to replace `alert` with `console.log`, shown below the text, what you think? 

Mobiles may be a concern.

**Comment by iliakan** [comment]
Replaced here: https://javascript.info/selection-range

**Comment by Violet-Bora-Lee** [comment]
I prefer Alsrtd as I usually read the tutorial on the mobile.

But if you change the 'console.log' styles and add the comments on the codeboxes, usere could get enough information without using dev tools.
